import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createServer } from 'vite';

const server = await createServer({ server: { middlewareMode: true, hmr: false, ws: false }, appType: 'custom' });
const { resolveCardArtwork, cardArtworkPlacement } = await server.ssrLoadModule('/src/models/cardArtwork.ts');
const { CARD_ARTWORK, CARD_RARITY_FINISH } = await server.ssrLoadModule('/src/data/cardAppearance.ts');
const { CARD_DEFINITIONS } = await server.ssrLoadModule('/src/data/cards.ts');
const { EVENT_BATTLES } = await server.ssrLoadModule('/src/data/eventBattles.ts');
const { STATUS_DESCRIPTIONS } = await server.ssrLoadModule('/src/data/statuses.ts');
await server.close();

test('file discovery falls back together with its placement, and missing art is normal', () => {
  const registry = { example: { normal: { scale: 0.4 }, tutorial: { scale: 0.25 } } };
  const files = new Set(['example_normal.png', 'example_tutorial.png', 'newCard_tutorial.png']);
  assert.deepEqual(resolveCardArtwork('example', 'tutorial', files, registry), { scale: 0.25, file: 'example_tutorial.png' });
  assert.deepEqual(resolveCardArtwork('example', 'normal', files, registry), { scale: 0.4, file: 'example_normal.png' });
  assert.deepEqual(resolveCardArtwork('example', 'anotherEvent', files, registry), { scale: 0.4, file: 'example_normal.png' });
  assert.equal(resolveCardArtwork('missing', 'tutorial', files, registry), undefined);
  assert.deepEqual(resolveCardArtwork('newCard', 'tutorial', files, registry), { file: 'newCard_tutorial.png' });
  files.delete('example_tutorial.png');
  assert.deepEqual(resolveCardArtwork('example', 'tutorial', files, registry), { scale: 0.4, file: 'example_normal.png' });
  const disk = new Set(fs.readdirSync('image/card'));
  assert.equal(resolveCardArtwork('rubOneOut', 'normal', disk), undefined);
  assert.equal(resolveCardArtwork('rubOneOut', 'tutorial', disk).file, 'rubOneOut_tutorial.png');
});

test('focus/offset/rotation/scale use image coordinates and do not depend on display zoom', () => {
  const pose = cardArtworkPlacement({ file: 'a.png', focusX: 500, focusY: 500, scale: 0.25, offsetX: 10, offsetY: -20, rotation: 90 }, 1024, 1400, 148, 220);
  assert.deepEqual(pose, { focusX: 500, focusY: 500, scale: 0.25, x: 10, y: -20, radians: Math.PI / 2 });
  assert.deepEqual(cardArtworkPlacement({ file: 'a.png' }, 1000, 2000, 148, 220), { focusX: 500, focusY: 1000, scale: 0.148, x: 0, y: 0, radians: 0 });
});

test('every current card has normal placement, even before its image exists', () => {
  assert.deepEqual(Object.keys(CARD_ARTWORK).sort(), Object.values(CARD_DEFINITIONS).map(c => c.id).sort());
  for (const [id, config] of Object.entries(CARD_ARTWORK)) {
    assert.ok(Object.values(CARD_DEFINITIONS).some(card => card.id === id), id);
    assert.ok(config.normal);
    for (const art of Object.values(config)) {
      assert.equal('file' in art, false);
      assert.ok(art.scale === undefined || art.scale > 0);
    }
  }
  for (const rarity of ['starter', 'common', 'uncommon', 'rare', 'event']) assert.ok(CARD_RARITY_FINISH[rarity]);
  assert.deepEqual(CARD_RARITY_FINISH.starter, CARD_RARITY_FINISH.common);
});

test('tutorial covers initial/event cards and cards generated by connection, arousal and Peak statuses', () => {
  const ids = new Set([...EVENT_BATTLES.tutorial.deckIds, ...EVENT_BATTLES.tutorial.beforeDrawEvents.flatMap(e => e.cardIds ?? [])]);
  for (const id of ['Horny', 'InHeat', 'Frustrated', 'DesperateToPeak', 'InsertV', 'InsertA', 'InsertM', 'MultiplePeak', 'PeakHell', 'MultiplePeaksTorture']) {
    for (const trigger of STATUS_DESCRIPTIONS[id].triggers ?? []) for (const effect of trigger.effects ?? []) {
      if (effect.kind === 'addCardToHand') ids.add(effect.cardId);
    }
  }
  for (const id of ids) assert.ok(CARD_ARTWORK[id]?.tutorial, `${id} needs tutorial placement`);
  for (const id of ['strike', 'handWork', 'cowgirlRiding', 'rubOneOut', 'seduction', 'rubOne', 'pullout', 'faint']) assert.ok(ids.has(id), id);
});
