import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createServer } from 'vite';

const server = await createServer({ server: { middlewareMode: true, hmr: false, ws: false }, appType: 'custom' });
const { resolveCardArtwork, resolveCardArtworkSource, cardArtworkPlacement } = await server.ssrLoadModule('/src/models/cardArtwork.ts');
const { CARD_ARTWORK, CARD_RARITY_FINISH } = await server.ssrLoadModule('/src/data/cardAppearance.ts');
const { cardArtworkSlot, cardArtworkCandidates } = await server.ssrLoadModule('/src/models/cardArtworkVariants.ts');
const { CARD_DEFINITIONS } = await server.ssrLoadModule('/src/data/cards.ts');
const { EVENT_BATTLES } = await server.ssrLoadModule('/src/data/eventBattles.ts');
const { STATUS_DESCRIPTIONS } = await server.ssrLoadModule('/src/data/statuses.ts');
await server.close();

test('file discovery falls back together with its placement, and missing art is normal', () => {
  const registry = { example: { normal: { scale: 0.4 }, tutorial: { scale: 0.25 } } };
  const files = new Set(['example_normal.png', 'example_tutorial.png', 'newCard_tutorial.png']);
  assert.deepEqual(resolveCardArtwork('example', 'tutorial', files, registry), { scale: 0.25, file: 'example_tutorial.png' });
  assert.deepEqual(resolveCardArtwork('example', 'normal', files, registry), { scale: 0.4, file: 'example_normal.png' });
  assert.deepEqual(resolveCardArtwork('example', 'anotherEvent', files, registry), { scale: 0.4, file: 'example_normal.png' });
  assert.equal(resolveCardArtwork('missing', 'tutorial', files, registry), undefined);
  assert.deepEqual(resolveCardArtwork('newCard', 'tutorial', files, registry), { file: 'newCard_tutorial.png' });
  files.delete('example_tutorial.png');
  assert.deepEqual(resolveCardArtwork('example', 'tutorial', files, registry), { scale: 0.4, file: 'example_normal.png' });
  const disk = new Set(fs.readdirSync('image/card'));
  assert.equal(resolveCardArtwork('rubOneOut', 'normal', disk), undefined);
  assert.equal(resolveCardArtwork('rubOneOut', 'tutorial', disk).file, 'rubOneOut_tutorial.png');
});

test('focus/offset/rotation/scale use image coordinates and do not depend on display zoom', () => {
  const pose = cardArtworkPlacement({ file: 'a.png', focusX: 500, focusY: 500, scale: 0.25, offsetX: 10, offsetY: -20, rotation: 90 }, 1024, 1400, 148, 220);
  assert.deepEqual(pose, { focusX: 500, focusY: 500, scale: 0.25, x: 10, y: -20, radians: Math.PI / 2 });
  assert.deepEqual(cardArtworkPlacement({ file: 'a.png' }, 1000, 2000, 148, 220), { focusX: 500, focusY: 1000, scale: 0.148, x: 0, y: 0, radians: 0 });
});

test('every current card has normal placement, even before its image exists', () => {
  assert.deepEqual(Object.keys(CARD_ARTWORK).sort(), Object.values(CARD_DEFINITIONS).map(c => c.id).sort());
  for (const id of Object.keys(CARD_ARTWORK)) {
    const {settings:config,error}=resolveCardArtworkSource(id);assert.equal(error,undefined);
    assert.ok(Object.values(CARD_DEFINITIONS).some(card => card.id === id), id);
    assert.ok(config.normal);
    for (const art of Object.values(config)) {
      assert.equal('file' in art, false);
      assert.ok(art.scale === undefined || art.scale > 0);
    }
  }
  for (const rarity of ['starter', 'common', 'uncommon', 'rare', 'event']) assert.ok(CARD_RARITY_FINISH[rarity]);
  assert.deepEqual(CARD_RARITY_FINISH.starter, CARD_RARITY_FINISH.common);
});

test('tutorial covers initial/event cards and cards generated by connection, arousal and orgasm statuses', () => {
  const ids = new Set([...EVENT_BATTLES.tutorial.deckIds, ...EVENT_BATTLES.tutorial.beforeDrawEvents.flatMap(e => e.cardIds ?? [])]);
  for (const id of ['Horny', 'InHeat', 'Frustrated', 'DesperateToCum', 'InsertV', 'InsertA', 'InsertM', 'MultipleOrgasm', 'OrgasmHell', 'MultipleOrgasmsTorture']) {
    for (const trigger of STATUS_DESCRIPTIONS[id].triggers ?? []) for (const effect of trigger.effects ?? []) {
      if (effect.kind === 'addCardToHand') ids.add(effect.cardId);
    }
  }
  for (const id of ids) assert.ok(resolveCardArtworkSource(id).settings?.tutorial, `${id} needs tutorial placement`);
  for (const id of ['strike', 'handjob', 'cowgirlRiding', 'rubOneOut', 'seduction', 'rubOne', 'pullout', 'faint']) assert.ok(ids.has(id), id);
});

test('aliases share source image and battle placement, including fallback and multi-hop references',()=>{
 const registry={original:{normal:{scale:.4},tutorial:{scale:.2,rotation:35,offsetX:12}},alias:'original',chain:'alias'};
 const files=new Set(['original_normal.png','original_tutorial.png','alias_tutorial.png']);
 for(const id of ['alias','chain']) {
  assert.deepEqual(resolveCardArtwork(id,'tutorial',files,registry),{file:'original_tutorial.png',...registry.original.tutorial});
  assert.deepEqual(resolveCardArtwork(id,'future',files,registry),{file:'original_normal.png',scale:.4});
 }
 registry.original.tutorial.offsetY=30;
 assert.equal(resolveCardArtwork('alias','tutorial',files,registry).offsetY,30);
 files.delete('original_tutorial.png');
 assert.deepEqual(resolveCardArtwork('alias','tutorial',files,registry),{file:'original_normal.png',scale:.4});
 files.delete('original_normal.png');assert.equal(resolveCardArtwork('alias','tutorial',files,registry),undefined);
 const disk=new Set(fs.readdirSync('image/card'));
 assert.equal(CARD_ARTWORK.rubOne,'rubOneOut');
 for(const battle of ['normal','tutorial'])assert.deepEqual(resolveCardArtwork('rubOne',battle,disk),resolveCardArtwork('rubOneOut',battle,disk));
});

test('invalid references never loop or silently use the alias own file',()=>{
 for(const registry of [{a:'a'},{a:'b',b:'a'},{a:'missing'},{a:''}]) {
  assert.ok(resolveCardArtworkSource('a',registry).error);
  assert.equal(resolveCardArtwork('a','normal',new Set(['a_normal.png']),registry),undefined);
 }
});

test('part-specific files use their own placement and fallback within the battle before normal',()=>{
 const registry={pullout:{tutorialA:{offsetX:10},tutorialV:{offsetX:20},tutorial:{offsetX:30},normalA:{offsetX:40},normalV:{offsetX:50},normal:{offsetX:60}}};
 const files=new Set(['pulloutA_tutorial.png','pulloutV_tutorial.png','pullout_tutorial.png','pulloutA_normal.png','pulloutV_normal.png','pullout_normal.png']);
 const check=(part,file,x)=>assert.deepEqual(resolveCardArtwork('pullout','tutorial',files,registry,part),{file,offsetX:x});
 check('A','pulloutA_tutorial.png',10);check('V','pulloutV_tutorial.png',20);
 files.delete('pulloutA_tutorial.png');check('A','pullout_tutorial.png',30);
 files.delete('pullout_tutorial.png');check('A','pulloutV_tutorial.png',20);
 files.delete('pulloutV_tutorial.png');check('A','pulloutA_normal.png',40);
 files.delete('pulloutA_normal.png');check('A','pullout_normal.png',60);
 files.delete('pullout_normal.png');check('A','pulloutV_normal.png',50);
 files.clear();assert.equal(resolveCardArtwork('pullout','tutorial',files,registry,'A'),undefined);
});

test('purge V/A/M uses the removal cause, and aliases share variant settings too',()=>{
 const registry={purge:{tutorialV:{rotation:1},tutorialA:{rotation:2},tutorialM:{rotation:3}},alias:'purge'};
 const files=new Set(['purgeV_tutorial.png','purgeA_tutorial.png','purgeM_tutorial.png']);
 for(const [status,rotation] of [['IntrudedV',1],['IntrudedA',2],['IntrudedM',3]]) {
  const part=STATUS_DESCRIPTIONS[status].epDamageParts[0];
  for(const card of ['purge','alias'])assert.deepEqual(resolveCardArtwork(card,'tutorial',files,registry,part),{file:`purge${part}_tutorial.png`,rotation});
 }
 files.delete('purgeA_tutorial.png');
 assert.equal(resolveCardArtwork('purge','tutorial',files,registry,'A').file,'purgeV_tutorial.png');
 assert.equal(resolveCardArtwork('purge','tutorial',files,registry,'A',{purge:['M','V','A']}).file,'purgeM_tutorial.png');
});

test('tool slot names and runtime filenames match; migrated V asset retains the existing placement',()=>{
 for(const card of ['pullout','purge'])for(const battle of ['normal','tutorial'])for(const part of ['V','A','M']) {
  const slot=cardArtworkSlot(card,battle+part,['V','A','M']);
  assert.equal(slot.file,`${card}${part}_${battle}.png`);assert.equal(slot.battleId,battle);assert.equal(slot.part,part);
 }
 const candidates=cardArtworkCandidates('purge','tutorial',['V','A','M'],'M');
 assert.deepEqual(candidates.map(c=>c.slot),['tutorialM','tutorial','tutorialV','tutorialA','normalM','normal','normalV','normalA']);
 const disk=new Set(fs.readdirSync('image/card'));
 assert.ok(disk.has('pulloutV_tutorial.png'));assert.ok(!disk.has('pullout_tutorial.png'));
 for(const part of ['V','A'])assert.deepEqual(resolveCardArtwork('pullout','tutorial',disk,undefined,part),{file:'pulloutV_tutorial.png',...CARD_ARTWORK.pullout.tutorialV});
 assert.equal(resolveCardArtwork('pullout','tutorial',disk).file,'pulloutV_tutorial.png');
});
